### ISSUE TITLE
Add go master to .travls.yml

### ISSUE THREAD

**Issue by davepuchyr** [iov-one/cosmos-sdk-crud#13]
It's important to build our code with go's master branch since go moves fairly quickly.  We need to add go master back to .travis.yml.

We need to make the linting and formatting conditional in .travis.yml since goimports is broken on go master.

**Comment by LeCodeurDuDimanche** [comment]
@davepuchyr we could also use `go: stable` rather than `go: master`, which is the latest stable release and should always be a suitable version for `goimports`
